run:
  build-tags:
    - bench
    - ""
  tests: true

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goheader
    - goprintffuncname
    - gosec
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - tagliatelle
    - thelper
    - unconvert
    - unparam
    - unused
    - whitespace
    - gci
    - gofmt
    - gofumpt

linters-settings:
  depguard:
    rules:
      Main:
        files:
          - $all
          - '!$test'
        allow:
          - $gostd
      Test:
        files:
          - $test
        allow:
          - $gostd
          - ://github.com
  funlen:
    lines: 150
    statements: 80

issues:
  exclude-use-default: false
  exclude-dirs:
    - third_party$
    - builtin$
    - examples$
  exclude-rules:
    # Исключения по пресетам перенесены в стандартные правила
    - preset: comments
    - preset: common-false-positives
    - preset: legacy
    - preset: std-error-handling
    # Ваше старое правило для тестовых файлов
    - path: _test\.go
      linters:
        - dupl
        - errcheck
        - gocyclo
        - gosec
