version: "2"

run:
  build-tags:
    - bench
    - ""
  tests: true

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    # - depguard
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goheader
    - goprintffuncname
    - gosec
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    # - revive
    - staticcheck
    - tagliatelle
    - thelper
    - unconvert
    - unparam
    - unused
    - whitespace
    # ⚠️ Из этой секции удалены gci, gofmt, gofumpt
  exclusions:
    rules:
      - linters:
          - revive
        text: "should have( a package)? comment"
      - linters:
          - revive
        text: "empty-block: this block is empty, you can remove it"
      - linters:
          - gosec
        text: "(G115|G404)"

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt

linters-settings:
  depguard:
    rules:
      main:
        list-mode: lax
        files:
          - "$all"
        # allow:
        #   - "$gostd"
        #   - "github.com/stretchr/testify"
        # deny: []
  
  gocognit:
    min-complexity: 40

  funlen:
    lines: 150
    statements: 80

issues:
  exclude-generated-by-default: true
  exclude-use-default: false
  exclude-dirs:
    - third_party$
    - builtin$
    - examples$
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - errcheck
        - gocyclo
        - gosec
    - linters: [revive]
      text: "exported (.+) should have comment"
    - linters: [revive]
      text: "package comment should be of the form"
    - linters: [revive]
      text: "should have a package comment"
    - linters: [staticcheck]
      text: "(ST1000|ST1020|ST1021|ST1022)"
    - linters: [gosec]
      text: "G103: Use of unsafe calls should be audited"
    - linters: [gosec]
      text: "G204: Subprocess launched with variable"
    - linters: [gosec]
      text: "G304: Potential file inclusion via variable"
    - linters: [govet]
      text: "(possible misuse of unsafe.Pointer|should have signature)"
    - linters: [gosec]
      text: "G104"
    - linters: [gosec]
      text: "G115"
    - linters: [gosec]
      text: "(G301|G302|G307): Expect (directory permissions to be 0750|file permissions to be 0600)"
    - linters: [errcheck]
      text: "(?i)Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*print(f|ln)?|os\\.(Un)?Setenv). is not checked"
