// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: api/EventsService.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	UserId        string                 `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_api_EventsService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_api_EventsService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_api_EventsService_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Event) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Event) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *Event) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Event) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreateEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	UserId        string                 `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventRequest) Reset() {
	*x = CreateEventRequest{}
	mi := &file_api_EventsService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventRequest) ProtoMessage() {}

func (x *CreateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_EventsService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventRequest.ProtoReflect.Descriptor instead.
func (*CreateEventRequest) Descriptor() ([]byte, []int) {
	return file_api_EventsService_proto_rawDescGZIP(), []int{1}
}

func (x *CreateEventRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateEventRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *CreateEventRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *CreateEventRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateEventRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreateEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventResponse) Reset() {
	*x = CreateEventResponse{}
	mi := &file_api_EventsService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventResponse) ProtoMessage() {}

func (x *CreateEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_EventsService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventResponse.ProtoReflect.Descriptor instead.
func (*CreateEventResponse) Descriptor() ([]byte, []int) {
	return file_api_EventsService_proto_rawDescGZIP(), []int{2}
}

func (x *CreateEventResponse) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type UpdateEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Event         *Event                 `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEventRequest) Reset() {
	*x = UpdateEventRequest{}
	mi := &file_api_EventsService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventRequest) ProtoMessage() {}

func (x *UpdateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_EventsService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventRequest.ProtoReflect.Descriptor instead.
func (*UpdateEventRequest) Descriptor() ([]byte, []int) {
	return file_api_EventsService_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateEventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateEventRequest) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type UpdateEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEventResponse) Reset() {
	*x = UpdateEventResponse{}
	mi := &file_api_EventsService_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventResponse) ProtoMessage() {}

func (x *UpdateEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_EventsService_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventResponse.ProtoReflect.Descriptor instead.
func (*UpdateEventResponse) Descriptor() ([]byte, []int) {
	return file_api_EventsService_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateEventResponse) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type DeleteEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventRequest) Reset() {
	*x = DeleteEventRequest{}
	mi := &file_api_EventsService_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventRequest) ProtoMessage() {}

func (x *DeleteEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_EventsService_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventRequest.ProtoReflect.Descriptor instead.
func (*DeleteEventRequest) Descriptor() ([]byte, []int) {
	return file_api_EventsService_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteEventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventResponse) Reset() {
	*x = DeleteEventResponse{}
	mi := &file_api_EventsService_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventResponse) ProtoMessage() {}

func (x *DeleteEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_EventsService_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventResponse.ProtoReflect.Descriptor instead.
func (*DeleteEventResponse) Descriptor() ([]byte, []int) {
	return file_api_EventsService_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type EventsForDayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Day           *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=day,proto3" json:"day,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventsForDayRequest) Reset() {
	*x = EventsForDayRequest{}
	mi := &file_api_EventsService_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventsForDayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsForDayRequest) ProtoMessage() {}

func (x *EventsForDayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_EventsService_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsForDayRequest.ProtoReflect.Descriptor instead.
func (*EventsForDayRequest) Descriptor() ([]byte, []int) {
	return file_api_EventsService_proto_rawDescGZIP(), []int{7}
}

func (x *EventsForDayRequest) GetDay() *timestamppb.Timestamp {
	if x != nil {
		return x.Day
	}
	return nil
}

type EventsForWeekRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WeekFirstDay  *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=week_first_day,json=weekFirstDay,proto3" json:"week_first_day,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventsForWeekRequest) Reset() {
	*x = EventsForWeekRequest{}
	mi := &file_api_EventsService_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventsForWeekRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsForWeekRequest) ProtoMessage() {}

func (x *EventsForWeekRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_EventsService_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsForWeekRequest.ProtoReflect.Descriptor instead.
func (*EventsForWeekRequest) Descriptor() ([]byte, []int) {
	return file_api_EventsService_proto_rawDescGZIP(), []int{8}
}

func (x *EventsForWeekRequest) GetWeekFirstDay() *timestamppb.Timestamp {
	if x != nil {
		return x.WeekFirstDay
	}
	return nil
}

type EventsForMonthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MonthFirstDay *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=month_first_day,json=monthFirstDay,proto3" json:"month_first_day,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventsForMonthRequest) Reset() {
	*x = EventsForMonthRequest{}
	mi := &file_api_EventsService_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventsForMonthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsForMonthRequest) ProtoMessage() {}

func (x *EventsForMonthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_EventsService_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsForMonthRequest.ProtoReflect.Descriptor instead.
func (*EventsForMonthRequest) Descriptor() ([]byte, []int) {
	return file_api_EventsService_proto_rawDescGZIP(), []int{9}
}

func (x *EventsForMonthRequest) GetMonthFirstDay() *timestamppb.Timestamp {
	if x != nil {
		return x.MonthFirstDay
	}
	return nil
}

type EventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventsResponse) Reset() {
	*x = EventsResponse{}
	mi := &file_api_EventsService_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsResponse) ProtoMessage() {}

func (x *EventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_EventsService_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsResponse.ProtoReflect.Descriptor instead.
func (*EventsResponse) Descriptor() ([]byte, []int) {
	return file_api_EventsService_proto_rawDescGZIP(), []int{10}
}

func (x *EventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_api_EventsService_proto protoreflect.FileDescriptor

const file_api_EventsService_proto_rawDesc = "" +
	"\n" +
	"\x17api/EventsService.proto\x12\x03api\x1a\x1fgoogle/protobuf/timestamp.proto\"\xda\x01\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\tR\x06userId\"\xd7\x01\n" +
	"\x12CreateEventRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\tR\x06userId\"7\n" +
	"\x13CreateEventResponse\x12 \n" +
	"\x05event\x18\x01 \x01(\v2\n" +
	".api.EventR\x05event\"F\n" +
	"\x12UpdateEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\x05event\x18\x02 \x01(\v2\n" +
	".api.EventR\x05event\"7\n" +
	"\x13UpdateEventResponse\x12 \n" +
	"\x05event\x18\x01 \x01(\v2\n" +
	".api.EventR\x05event\"$\n" +
	"\x12DeleteEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"/\n" +
	"\x13DeleteEventResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"C\n" +
	"\x13EventsForDayRequest\x12,\n" +
	"\x03day\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x03day\"X\n" +
	"\x14EventsForWeekRequest\x12@\n" +
	"\x0eweek_first_day\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\fweekFirstDay\"[\n" +
	"\x15EventsForMonthRequest\x12B\n" +
	"\x0fmonth_first_day\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\rmonthFirstDay\"4\n" +
	"\x0eEventsResponse\x12\"\n" +
	"\x06events\x18\x01 \x03(\v2\n" +
	".api.EventR\x06events2\x98\x03\n" +
	"\rEventsService\x12@\n" +
	"\vCreateEvent\x12\x17.api.CreateEventRequest\x1a\x18.api.CreateEventResponse\x12@\n" +
	"\vUpdateEvent\x12\x17.api.UpdateEventRequest\x1a\x18.api.UpdateEventResponse\x12@\n" +
	"\vDeleteEvent\x12\x17.api.DeleteEventRequest\x1a\x18.api.DeleteEventResponse\x12=\n" +
	"\fEventsForDay\x12\x18.api.EventsForDayRequest\x1a\x13.api.EventsResponse\x12?\n" +
	"\rEventsForWeek\x12\x19.api.EventsForWeekRequest\x1a\x13.api.EventsResponse\x12A\n" +
	"\x0eEventsForMonth\x12\x1a.api.EventsForMonthRequest\x1a\x13.api.EventsResponseB#Z!hw12_13_14_15_16_calendar/api;apib\x06proto3"

var (
	file_api_EventsService_proto_rawDescOnce sync.Once
	file_api_EventsService_proto_rawDescData []byte
)

func file_api_EventsService_proto_rawDescGZIP() []byte {
	file_api_EventsService_proto_rawDescOnce.Do(func() {
		file_api_EventsService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_EventsService_proto_rawDesc), len(file_api_EventsService_proto_rawDesc)))
	})
	return file_api_EventsService_proto_rawDescData
}

var file_api_EventsService_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_EventsService_proto_goTypes = []any{
	(*Event)(nil),                 // 0: api.Event
	(*CreateEventRequest)(nil),    // 1: api.CreateEventRequest
	(*CreateEventResponse)(nil),   // 2: api.CreateEventResponse
	(*UpdateEventRequest)(nil),    // 3: api.UpdateEventRequest
	(*UpdateEventResponse)(nil),   // 4: api.UpdateEventResponse
	(*DeleteEventRequest)(nil),    // 5: api.DeleteEventRequest
	(*DeleteEventResponse)(nil),   // 6: api.DeleteEventResponse
	(*EventsForDayRequest)(nil),   // 7: api.EventsForDayRequest
	(*EventsForWeekRequest)(nil),  // 8: api.EventsForWeekRequest
	(*EventsForMonthRequest)(nil), // 9: api.EventsForMonthRequest
	(*EventsResponse)(nil),        // 10: api.EventsResponse
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_api_EventsService_proto_depIdxs = []int32{
	11, // 0: api.Event.start_time:type_name -> google.protobuf.Timestamp
	11, // 1: api.Event.end_time:type_name -> google.protobuf.Timestamp
	11, // 2: api.CreateEventRequest.start_time:type_name -> google.protobuf.Timestamp
	11, // 3: api.CreateEventRequest.end_time:type_name -> google.protobuf.Timestamp
	0,  // 4: api.CreateEventResponse.event:type_name -> api.Event
	0,  // 5: api.UpdateEventRequest.event:type_name -> api.Event
	0,  // 6: api.UpdateEventResponse.event:type_name -> api.Event
	11, // 7: api.EventsForDayRequest.day:type_name -> google.protobuf.Timestamp
	11, // 8: api.EventsForWeekRequest.week_first_day:type_name -> google.protobuf.Timestamp
	11, // 9: api.EventsForMonthRequest.month_first_day:type_name -> google.protobuf.Timestamp
	0,  // 10: api.EventsResponse.events:type_name -> api.Event
	1,  // 11: api.EventsService.CreateEvent:input_type -> api.CreateEventRequest
	3,  // 12: api.EventsService.UpdateEvent:input_type -> api.UpdateEventRequest
	5,  // 13: api.EventsService.DeleteEvent:input_type -> api.DeleteEventRequest
	7,  // 14: api.EventsService.EventsForDay:input_type -> api.EventsForDayRequest
	8,  // 15: api.EventsService.EventsForWeek:input_type -> api.EventsForWeekRequest
	9,  // 16: api.EventsService.EventsForMonth:input_type -> api.EventsForMonthRequest
	2,  // 17: api.EventsService.CreateEvent:output_type -> api.CreateEventResponse
	4,  // 18: api.EventsService.UpdateEvent:output_type -> api.UpdateEventResponse
	6,  // 19: api.EventsService.DeleteEvent:output_type -> api.DeleteEventResponse
	10, // 20: api.EventsService.EventsForDay:output_type -> api.EventsResponse
	10, // 21: api.EventsService.EventsForWeek:output_type -> api.EventsResponse
	10, // 22: api.EventsService.EventsForMonth:output_type -> api.EventsResponse
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_api_EventsService_proto_init() }
func file_api_EventsService_proto_init() {
	if File_api_EventsService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_EventsService_proto_rawDesc), len(file_api_EventsService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_EventsService_proto_goTypes,
		DependencyIndexes: file_api_EventsService_proto_depIdxs,
		MessageInfos:      file_api_EventsService_proto_msgTypes,
	}.Build()
	File_api_EventsService_proto = out.File
	file_api_EventsService_proto_goTypes = nil
	file_api_EventsService_proto_depIdxs = nil
}
